### ISSUE TITLE
wordpress inner post structure

### ISSUE THREAD

**Issue by br092616** [pwrstudio/marenluebbketidow#8]
- switch "full title" with headline/post name
(headline/post name in left menu with function to add italics and bold, "full title" on top of post in the main column with function to add italics and bold)

**Comment by br092616** [comment]
- take out "add pdf"? I think it can be added simply as media/link?

**Comment by pwrstudio** [comment]
"Add pdf" is removed.

Regarding point one:

Do you mean that there should be two fields: one called **headline/post name** that should be shown in the left column on the frontend, and one named **full title** shown at the top of the post in the rmain column on the frontend? Both with the option of adding italics/bold styling?

**Comment by br092616** [comment]
best would be if the title in the left column (we only need italics here) of the frontend is displayed as the title of the post in the backend; and that there is an additional title field that in the frontend is displayed in the main column as the headline. This could also be simply part of the main text…?

**Comment by pwrstudio** [comment]
> I think the title displayed in the list of posts should be the title from the left menu. if you look at http://marenluebbketidow.com/texts#%e2%80%89headline-hier, the post won't display. I think I changed the headline after publishing...

> best would be if the title in the left column (we only need italics here) of the frontend is displayed as the title of the post in the backend; and that there is an additional title field that in the frontend is displayed in the main column as the headline. This could also be simply part of the main text…?

Regarding the title(s):
The main **title field** (where it says _test2_ here) will not allow you to do styling, hence why I added the **full title field**.
 
![screen shot 2016-11-30 at 15 08 25](https://cloud.githubusercontent.com/assets/8209990/20755358/f812cfe0-b70e-11e6-9ede-01da230c122b.png)

So there is now a short title - used for identifing the post internally - and a full title that is shown on the front-page.

I have changed it so that both the short and long titles is shown in the post list in the backend:
   
![screen shot 2016-11-30 at 15 22 43](https://cloud.githubusercontent.com/assets/8209990/20755897/ed772278-b710-11e6-9226-a86f1d7de06c.png)

About the left column title vs. right column title:
They are now both taken from the **full-title** field, with a hard-coded bold style being applied to the right column title. Is there any case when the right hand title should not be bold?

**Comment by br092616** [comment]
don't think we need a short title, if you can take it out?

**Comment by pwrstudio** [comment]
The thing is, the main title is necessary for wordpress to identify the post. It needs a short, unstyled string to name the post.

**Comment by br092616** [comment]
ok!

**Comment by br092616** [comment]
in the text editor, I had difficulties to add a separate paragraph without indent, or just a link detached from the text without the indent from the previous paragraph, even with clearing the formatting. The only way I could put it was to apply a format from the drop down, all a bit confusing (see image).

- would it be possible to take out all unnecessary formats away from the dropdown-menu?
- would it be possible to add a format "no indent"?

thanks!

<img width="1361" alt="screen shot 2016-12-05 at 08 17 58" src="https://cloud.githubusercontent.com/assets/22127585/20876697/0ef5cea2-bac4-11e6-99b5-bf42bdeaf7c0.png">

**Comment by br092616** [comment]
not sure if you had seen this, and what you think about it. if too much work I can just tell Maren also. 

Also, if possible in the frontend, in the main column could we hide the headline? Maren would always add the headline to the main text field and put it bold herself manually, sometimes with slightly different content from the left menu. That would be more practical for her.

thx

**Comment by pwrstudio** [comment]
changed it now so that if you add an extra newline (hit enter/return) the next paragraph will not have any **indent**. so only paragraphs immediately following another paragraph will have an indent, as per normal typographic practice.

for the **title**: it is now remove: she can add it herself in the main content input area.
